// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { APIResource } from '../../core/resource';
import * as AccountsAPI from './accounts';
import {
  Account,
  AccountBalances,
  AccountBalancesSod,
  AccountGetAccountBalancesParams,
  AccountGetAccountBalancesResponse,
  AccountGetAccountByIDResponse,
  AccountGetAccountsParams,
  AccountGetAccountsResponse,
  AccountGetPortfolioHistoryParams,
  AccountGetPortfolioHistoryResponse,
  AccountList,
  AccountPatchAccountByIDParams,
  AccountPatchAccountByIDResponse,
  AccountSettings,
  AccountStatus,
  AccountSubtype,
  AccountType,
  Accounts,
  MarginDetails,
  MarginDetailsUsage,
  MarginSessionDetails,
  MarginTopContributor,
  MarginType,
  PortfolioHistoryResponse,
  PortfolioHistorySegment,
  RiskSettings,
} from './accounts';
import * as APIVersionAPI from './api-version';
import { APIVersion, APIVersionGetVersionResponse, Version } from './api-version';
import * as CalendarAPI from './calendar';
import {
  Calendar,
  CalendarGetClockResponse,
  CalendarGetMarketHoursCalendarParams,
  CalendarGetMarketHoursCalendarResponse,
  ClockDetail,
  DayType,
  MarketHoursDetail,
  MarketHoursDetailList,
  MarketSessionType,
  MarketStatus,
  MarketType,
  SessionSchedule,
  TradingSessions,
} from './calendar';
import * as InstrumentsAPI from './instruments';
import {
  ContractType,
  ExerciseStyle,
  Instrument,
  InstrumentCore,
  InstrumentCoreList,
  InstrumentGetInstrumentByIDParams,
  InstrumentGetInstrumentByIDResponse,
  InstrumentGetInstrumentsParams,
  InstrumentGetInstrumentsResponse,
  InstrumentGetOptionContractsParams,
  InstrumentGetOptionContractsResponse,
  InstrumentSearchInstrumentsParams,
  InstrumentSearchInstrumentsResponse,
  Instruments,
  ListingType,
  OptionsContract,
  OptionsContractList,
} from './instruments';
import * as OrdersAPI from './orders';
import {
  CancelOrderRequest,
  Execution,
  ExecutionList,
  InstrumentIDOrSymbol,
  NewOrderRequest,
  Order,
  OrderCancelAllOpenOrdersParams,
  OrderCancelAllOpenOrdersResponse,
  OrderCancelOpenOrderParams,
  OrderCancelOpenOrderResponse,
  OrderGetExecutionsParams,
  OrderGetExecutionsResponse,
  OrderGetOrderByIDParams,
  OrderGetOrderByIDResponse,
  OrderGetOrdersParams,
  OrderGetOrdersResponse,
  OrderList,
  OrderReplaceOrderParams,
  OrderReplaceOrderResponse,
  OrderStatus,
  OrderSubmitOrdersParams,
  OrderSubmitOrdersResponse,
  OrderType,
  Orders,
  PositionEffect,
  QueueState,
  RequestOrderType,
  RequestTimeInForce,
  Side,
  TimeInForce,
  TrailingOffsetType,
} from './orders';
import * as PositionsAPI from './positions';
import {
  Position,
  PositionCancelPositionInstructionParams,
  PositionCancelPositionInstructionResponse,
  PositionClosePositionParams,
  PositionClosePositionResponse,
  PositionClosePositionsParams,
  PositionClosePositionsResponse,
  PositionGetPositionInstructionsParams,
  PositionGetPositionInstructionsResponse,
  PositionGetPositionsParams,
  PositionGetPositionsResponse,
  PositionInstruction,
  PositionInstructionList,
  PositionInstructionStatus,
  PositionInstructionType,
  PositionList,
  PositionSubmitPositionInstructionsParams,
  PositionSubmitPositionInstructionsResponse,
  PositionType,
  Positions,
} from './positions';
import * as ScreenerAPI from './screener';
import {
  FieldLookback,
  FieldPeriod,
  FieldRef,
  FieldType,
  FilterOpSpec,
  FilterOperator,
  FilterValue,
  Modifier,
  ModifierOp,
  OperatorArg,
  Screener,
  ScreenerColumn,
  ScreenerCreateScreenerParams,
  ScreenerCreateScreenerResponse,
  ScreenerEntry,
  ScreenerEntryList,
  ScreenerFilter,
  ScreenerGetScreenerByIDResponse,
  ScreenerGetScreenersResponse,
  ScreenerReplaceScreenerParams,
  ScreenerReplaceScreenerResponse,
  ScreenerRow,
  ScreenerRowList,
  ScreenerSearchScreenerParams,
  ScreenerSearchScreenerResponse,
  SearchFilter,
  SortSpec,
  Variable,
} from './screener';
import * as WatchlistAPI from './watchlist';
import {
  AddWatchlistItemData,
  Watchlist,
  WatchlistAddWatchlistItemParams,
  WatchlistAddWatchlistItemResponse,
  WatchlistCreateWatchlistParams,
  WatchlistCreateWatchlistResponse,
  WatchlistDeleteWatchlistItemParams,
  WatchlistDeleteWatchlistItemResponse,
  WatchlistDeleteWatchlistResponse,
  WatchlistDetail,
  WatchlistEntry,
  WatchlistEntryList,
  WatchlistGetWatchlistByIDResponse,
  WatchlistGetWatchlistsParams,
  WatchlistGetWatchlistsResponse,
  WatchlistItemEntry,
} from './watchlist';
import * as InstrumentDataAPI from './instrument-data/instrument-data';
import {
  AllEventsEventType,
  AnalystDistribution,
  AnalystRating,
  FiscalPeriodType,
  InstrumentAllEventsData,
  InstrumentAnalystConsensus,
  InstrumentBalanceSheetStatement,
  InstrumentBalanceSheetStatementList,
  InstrumentCashFlowStatement,
  InstrumentCashFlowStatementList,
  InstrumentData,
  InstrumentDataGetAllInstrumentEventsParams,
  InstrumentDataGetAllInstrumentEventsResponse,
  InstrumentDataGetInstrumentAnalystConsensusParams,
  InstrumentDataGetInstrumentAnalystConsensusResponse,
  InstrumentDataGetInstrumentBalanceSheetStatementsParams,
  InstrumentDataGetInstrumentBalanceSheetStatementsResponse,
  InstrumentDataGetInstrumentCashFlowStatementsParams,
  InstrumentDataGetInstrumentCashFlowStatementsResponse,
  InstrumentDataGetInstrumentEventsParams,
  InstrumentDataGetInstrumentEventsResponse,
  InstrumentDataGetInstrumentFundamentalsResponse,
  InstrumentDataGetInstrumentIncomeStatementsParams,
  InstrumentDataGetInstrumentIncomeStatementsResponse,
  InstrumentDividendEvent,
  InstrumentEarnings,
  InstrumentEventEnvelope,
  InstrumentEventIpoItem,
  InstrumentEventsByDate,
  InstrumentEventsData,
  InstrumentFundamentals,
  InstrumentIncomeStatement,
  InstrumentIncomeStatementList,
  InstrumentSplitEvent,
  PriceTarget,
} from './instrument-data/instrument-data';
import * as OmniAIAPI from './omni-ai/omni-ai';
import {
  ActionButton,
  ChartPayload,
  ChartPoint,
  ChartSeries,
  ContentPartChartPayload,
  ContentPartCustomPayload,
  ContentPartStructuredActionPayload,
  ContentPartSuggestedActionsPayload,
  ContentPartTextPayload,
  ContentPartThinkingPayload,
  DataChart,
  EntitlementAgreementKey,
  EntitlementCode,
  OmniAI,
  OpenChartAction,
  OpenEntitlementConsentAction,
  OpenScreenerAction,
  PrefillCancelOrderAction,
  PrefillNewOrderAction,
  PrefillOrderAction,
  PromptButtonAction,
  StructuredAction,
  StructuredActionButtonAction,
  SuggestedActionsPayload,
} from './omni-ai/omni-ai';

export class V1 extends APIResource {
  accounts: AccountsAPI.Accounts = new AccountsAPI.Accounts(this._client);
  apiVersion: APIVersionAPI.APIVersion = new APIVersionAPI.APIVersion(this._client);
  calendar: CalendarAPI.Calendar = new CalendarAPI.Calendar(this._client);
  instrumentData: InstrumentDataAPI.InstrumentData = new InstrumentDataAPI.InstrumentData(this._client);
  instruments: InstrumentsAPI.Instruments = new InstrumentsAPI.Instruments(this._client);
  omniAI: OmniAIAPI.OmniAI = new OmniAIAPI.OmniAI(this._client);
  orders: OrdersAPI.Orders = new OrdersAPI.Orders(this._client);
  positions: PositionsAPI.Positions = new PositionsAPI.Positions(this._client);
  screener: ScreenerAPI.Screener = new ScreenerAPI.Screener(this._client);
  watchlist: WatchlistAPI.Watchlist = new WatchlistAPI.Watchlist(this._client);
}

/**
 * Security type
 */
export type SecurityType = 'COMMON_STOCK' | 'OPTION' | 'CASH';

/**
 * Sort direction sorted results
 */
export type SortDirection = 'ASC' | 'DESC';

V1.Accounts = Accounts;
V1.APIVersion = APIVersion;
V1.Calendar = Calendar;
V1.InstrumentData = InstrumentData;
V1.Instruments = Instruments;
V1.OmniAI = OmniAI;
V1.Orders = Orders;
V1.Positions = Positions;
V1.Screener = Screener;
V1.Watchlist = Watchlist;

export declare namespace V1 {
  export { type SecurityType as SecurityType, type SortDirection as SortDirection };

  export {
    Accounts as Accounts,
    type Account as Account,
    type AccountBalances as AccountBalances,
    type AccountBalancesSod as AccountBalancesSod,
    type AccountList as AccountList,
    type AccountSettings as AccountSettings,
    type AccountStatus as AccountStatus,
    type AccountSubtype as AccountSubtype,
    type AccountType as AccountType,
    type MarginDetails as MarginDetails,
    type MarginDetailsUsage as MarginDetailsUsage,
    type MarginSessionDetails as MarginSessionDetails,
    type MarginTopContributor as MarginTopContributor,
    type MarginType as MarginType,
    type PortfolioHistoryResponse as PortfolioHistoryResponse,
    type PortfolioHistorySegment as PortfolioHistorySegment,
    type RiskSettings as RiskSettings,
    type AccountGetAccountBalancesResponse as AccountGetAccountBalancesResponse,
    type AccountGetAccountByIDResponse as AccountGetAccountByIDResponse,
    type AccountGetAccountsResponse as AccountGetAccountsResponse,
    type AccountGetPortfolioHistoryResponse as AccountGetPortfolioHistoryResponse,
    type AccountPatchAccountByIDResponse as AccountPatchAccountByIDResponse,
    type AccountGetAccountBalancesParams as AccountGetAccountBalancesParams,
    type AccountGetAccountsParams as AccountGetAccountsParams,
    type AccountGetPortfolioHistoryParams as AccountGetPortfolioHistoryParams,
    type AccountPatchAccountByIDParams as AccountPatchAccountByIDParams,
  };

  export {
    APIVersion as APIVersion,
    type Version as Version,
    type APIVersionGetVersionResponse as APIVersionGetVersionResponse,
  };

  export {
    Calendar as Calendar,
    type ClockDetail as ClockDetail,
    type DayType as DayType,
    type MarketHoursDetail as MarketHoursDetail,
    type MarketHoursDetailList as MarketHoursDetailList,
    type MarketSessionType as MarketSessionType,
    type MarketStatus as MarketStatus,
    type MarketType as MarketType,
    type SessionSchedule as SessionSchedule,
    type TradingSessions as TradingSessions,
    type CalendarGetClockResponse as CalendarGetClockResponse,
    type CalendarGetMarketHoursCalendarResponse as CalendarGetMarketHoursCalendarResponse,
    type CalendarGetMarketHoursCalendarParams as CalendarGetMarketHoursCalendarParams,
  };

  export {
    InstrumentData as InstrumentData,
    type AllEventsEventType as AllEventsEventType,
    type AnalystDistribution as AnalystDistribution,
    type AnalystRating as AnalystRating,
    type FiscalPeriodType as FiscalPeriodType,
    type InstrumentAllEventsData as InstrumentAllEventsData,
    type InstrumentAnalystConsensus as InstrumentAnalystConsensus,
    type InstrumentBalanceSheetStatement as InstrumentBalanceSheetStatement,
    type InstrumentBalanceSheetStatementList as InstrumentBalanceSheetStatementList,
    type InstrumentCashFlowStatement as InstrumentCashFlowStatement,
    type InstrumentCashFlowStatementList as InstrumentCashFlowStatementList,
    type InstrumentDividendEvent as InstrumentDividendEvent,
    type InstrumentEarnings as InstrumentEarnings,
    type InstrumentEventEnvelope as InstrumentEventEnvelope,
    type InstrumentEventIpoItem as InstrumentEventIpoItem,
    type InstrumentEventsByDate as InstrumentEventsByDate,
    type InstrumentEventsData as InstrumentEventsData,
    type InstrumentFundamentals as InstrumentFundamentals,
    type InstrumentIncomeStatement as InstrumentIncomeStatement,
    type InstrumentIncomeStatementList as InstrumentIncomeStatementList,
    type InstrumentSplitEvent as InstrumentSplitEvent,
    type PriceTarget as PriceTarget,
    type InstrumentDataGetAllInstrumentEventsResponse as InstrumentDataGetAllInstrumentEventsResponse,
    type InstrumentDataGetInstrumentAnalystConsensusResponse as InstrumentDataGetInstrumentAnalystConsensusResponse,
    type InstrumentDataGetInstrumentBalanceSheetStatementsResponse as InstrumentDataGetInstrumentBalanceSheetStatementsResponse,
    type InstrumentDataGetInstrumentCashFlowStatementsResponse as InstrumentDataGetInstrumentCashFlowStatementsResponse,
    type InstrumentDataGetInstrumentEventsResponse as InstrumentDataGetInstrumentEventsResponse,
    type InstrumentDataGetInstrumentFundamentalsResponse as InstrumentDataGetInstrumentFundamentalsResponse,
    type InstrumentDataGetInstrumentIncomeStatementsResponse as InstrumentDataGetInstrumentIncomeStatementsResponse,
    type InstrumentDataGetAllInstrumentEventsParams as InstrumentDataGetAllInstrumentEventsParams,
    type InstrumentDataGetInstrumentAnalystConsensusParams as InstrumentDataGetInstrumentAnalystConsensusParams,
    type InstrumentDataGetInstrumentBalanceSheetStatementsParams as InstrumentDataGetInstrumentBalanceSheetStatementsParams,
    type InstrumentDataGetInstrumentCashFlowStatementsParams as InstrumentDataGetInstrumentCashFlowStatementsParams,
    type InstrumentDataGetInstrumentEventsParams as InstrumentDataGetInstrumentEventsParams,
    type InstrumentDataGetInstrumentIncomeStatementsParams as InstrumentDataGetInstrumentIncomeStatementsParams,
  };

  export {
    Instruments as Instruments,
    type ContractType as ContractType,
    type ExerciseStyle as ExerciseStyle,
    type Instrument as Instrument,
    type InstrumentCore as InstrumentCore,
    type InstrumentCoreList as InstrumentCoreList,
    type ListingType as ListingType,
    type OptionsContract as OptionsContract,
    type OptionsContractList as OptionsContractList,
    type InstrumentGetInstrumentByIDResponse as InstrumentGetInstrumentByIDResponse,
    type InstrumentGetInstrumentsResponse as InstrumentGetInstrumentsResponse,
    type InstrumentGetOptionContractsResponse as InstrumentGetOptionContractsResponse,
    type InstrumentSearchInstrumentsResponse as InstrumentSearchInstrumentsResponse,
    type InstrumentGetInstrumentByIDParams as InstrumentGetInstrumentByIDParams,
    type InstrumentGetInstrumentsParams as InstrumentGetInstrumentsParams,
    type InstrumentGetOptionContractsParams as InstrumentGetOptionContractsParams,
    type InstrumentSearchInstrumentsParams as InstrumentSearchInstrumentsParams,
  };

  export {
    OmniAI as OmniAI,
    type ActionButton as ActionButton,
    type ChartPayload as ChartPayload,
    type ChartPoint as ChartPoint,
    type ChartSeries as ChartSeries,
    type ContentPartChartPayload as ContentPartChartPayload,
    type ContentPartCustomPayload as ContentPartCustomPayload,
    type ContentPartStructuredActionPayload as ContentPartStructuredActionPayload,
    type ContentPartSuggestedActionsPayload as ContentPartSuggestedActionsPayload,
    type ContentPartTextPayload as ContentPartTextPayload,
    type ContentPartThinkingPayload as ContentPartThinkingPayload,
    type DataChart as DataChart,
    type EntitlementAgreementKey as EntitlementAgreementKey,
    type EntitlementCode as EntitlementCode,
    type OpenChartAction as OpenChartAction,
    type OpenEntitlementConsentAction as OpenEntitlementConsentAction,
    type OpenScreenerAction as OpenScreenerAction,
    type PrefillCancelOrderAction as PrefillCancelOrderAction,
    type PrefillNewOrderAction as PrefillNewOrderAction,
    type PrefillOrderAction as PrefillOrderAction,
    type PromptButtonAction as PromptButtonAction,
    type StructuredAction as StructuredAction,
    type StructuredActionButtonAction as StructuredActionButtonAction,
    type SuggestedActionsPayload as SuggestedActionsPayload,
  };

  export {
    Orders as Orders,
    type CancelOrderRequest as CancelOrderRequest,
    type Execution as Execution,
    type ExecutionList as ExecutionList,
    type InstrumentIDOrSymbol as InstrumentIDOrSymbol,
    type NewOrderRequest as NewOrderRequest,
    type Order as Order,
    type OrderList as OrderList,
    type OrderStatus as OrderStatus,
    type OrderType as OrderType,
    type PositionEffect as PositionEffect,
    type QueueState as QueueState,
    type RequestOrderType as RequestOrderType,
    type RequestTimeInForce as RequestTimeInForce,
    type Side as Side,
    type TimeInForce as TimeInForce,
    type TrailingOffsetType as TrailingOffsetType,
    type OrderCancelAllOpenOrdersResponse as OrderCancelAllOpenOrdersResponse,
    type OrderCancelOpenOrderResponse as OrderCancelOpenOrderResponse,
    type OrderGetExecutionsResponse as OrderGetExecutionsResponse,
    type OrderGetOrderByIDResponse as OrderGetOrderByIDResponse,
    type OrderGetOrdersResponse as OrderGetOrdersResponse,
    type OrderReplaceOrderResponse as OrderReplaceOrderResponse,
    type OrderSubmitOrdersResponse as OrderSubmitOrdersResponse,
    type OrderCancelAllOpenOrdersParams as OrderCancelAllOpenOrdersParams,
    type OrderCancelOpenOrderParams as OrderCancelOpenOrderParams,
    type OrderGetExecutionsParams as OrderGetExecutionsParams,
    type OrderGetOrderByIDParams as OrderGetOrderByIDParams,
    type OrderGetOrdersParams as OrderGetOrdersParams,
    type OrderReplaceOrderParams as OrderReplaceOrderParams,
    type OrderSubmitOrdersParams as OrderSubmitOrdersParams,
  };

  export {
    Positions as Positions,
    type Position as Position,
    type PositionInstruction as PositionInstruction,
    type PositionInstructionList as PositionInstructionList,
    type PositionInstructionStatus as PositionInstructionStatus,
    type PositionInstructionType as PositionInstructionType,
    type PositionList as PositionList,
    type PositionType as PositionType,
    type PositionCancelPositionInstructionResponse as PositionCancelPositionInstructionResponse,
    type PositionClosePositionResponse as PositionClosePositionResponse,
    type PositionClosePositionsResponse as PositionClosePositionsResponse,
    type PositionGetPositionInstructionsResponse as PositionGetPositionInstructionsResponse,
    type PositionGetPositionsResponse as PositionGetPositionsResponse,
    type PositionSubmitPositionInstructionsResponse as PositionSubmitPositionInstructionsResponse,
    type PositionCancelPositionInstructionParams as PositionCancelPositionInstructionParams,
    type PositionClosePositionParams as PositionClosePositionParams,
    type PositionClosePositionsParams as PositionClosePositionsParams,
    type PositionGetPositionInstructionsParams as PositionGetPositionInstructionsParams,
    type PositionGetPositionsParams as PositionGetPositionsParams,
    type PositionSubmitPositionInstructionsParams as PositionSubmitPositionInstructionsParams,
  };

  export {
    Screener as Screener,
    type FieldLookback as FieldLookback,
    type FieldPeriod as FieldPeriod,
    type FieldRef as FieldRef,
    type FieldType as FieldType,
    type FilterOpSpec as FilterOpSpec,
    type FilterOperator as FilterOperator,
    type FilterValue as FilterValue,
    type Modifier as Modifier,
    type ModifierOp as ModifierOp,
    type OperatorArg as OperatorArg,
    type ScreenerColumn as ScreenerColumn,
    type ScreenerEntry as ScreenerEntry,
    type ScreenerEntryList as ScreenerEntryList,
    type ScreenerFilter as ScreenerFilter,
    type ScreenerRow as ScreenerRow,
    type ScreenerRowList as ScreenerRowList,
    type SearchFilter as SearchFilter,
    type SortSpec as SortSpec,
    type Variable as Variable,
    type ScreenerCreateScreenerResponse as ScreenerCreateScreenerResponse,
    type ScreenerGetScreenerByIDResponse as ScreenerGetScreenerByIDResponse,
    type ScreenerGetScreenersResponse as ScreenerGetScreenersResponse,
    type ScreenerReplaceScreenerResponse as ScreenerReplaceScreenerResponse,
    type ScreenerSearchScreenerResponse as ScreenerSearchScreenerResponse,
    type ScreenerCreateScreenerParams as ScreenerCreateScreenerParams,
    type ScreenerReplaceScreenerParams as ScreenerReplaceScreenerParams,
    type ScreenerSearchScreenerParams as ScreenerSearchScreenerParams,
  };

  export {
    Watchlist as Watchlist,
    type AddWatchlistItemData as AddWatchlistItemData,
    type WatchlistDetail as WatchlistDetail,
    type WatchlistEntry as WatchlistEntry,
    type WatchlistEntryList as WatchlistEntryList,
    type WatchlistItemEntry as WatchlistItemEntry,
    type WatchlistAddWatchlistItemResponse as WatchlistAddWatchlistItemResponse,
    type WatchlistCreateWatchlistResponse as WatchlistCreateWatchlistResponse,
    type WatchlistDeleteWatchlistResponse as WatchlistDeleteWatchlistResponse,
    type WatchlistDeleteWatchlistItemResponse as WatchlistDeleteWatchlistItemResponse,
    type WatchlistGetWatchlistByIDResponse as WatchlistGetWatchlistByIDResponse,
    type WatchlistGetWatchlistsResponse as WatchlistGetWatchlistsResponse,
    type WatchlistAddWatchlistItemParams as WatchlistAddWatchlistItemParams,
    type WatchlistCreateWatchlistParams as WatchlistCreateWatchlistParams,
    type WatchlistDeleteWatchlistItemParams as WatchlistDeleteWatchlistItemParams,
    type WatchlistGetWatchlistsParams as WatchlistGetWatchlistsParams,
  };
}
